### ISSUE TITLE
如何设置点击图片不自动放大

### ISSUE THREAD

**Issue by BackToHappyBear** [ifanrx/wxParser-plugin#12]
enablePreviewImage默认是开启的，如何关闭

**Comment by lpbottle** [comment]
同问，我也碰到这个问题，图片链接会先预览图片，然后才跳转

**Comment by voglinde** [comment]
同问，然后默默换成文件版……

**Comment by bestyxie** [comment]
最新版本增加了 image-preview 属性设置是否点击预览图片

**Comment by WuJiY** [comment]
好像没有效果

**Comment by fuguxu** [comment]
image-preview貌似不生效

**Comment by ancelee** [comment]
image-preview不生效的，调用版本改成0.3.1就可以了，也没有一个版本说明

**Comment by ancelee** [comment]
image-preview不生效的，调用版本改成0.3.1就可以了，也没有一个版本说明
