### ISSUE TITLE
插件未授权使用

### ISSUE THREAD

**Issue by songzeng2016** [ifanrx/wxParser-plugin#16]
报错： 插件未授权使用

**Comment by songzeng2016** [comment]
@woodccc 暂未解决

**Comment by jiandandkl** [comment]
也曾遇到这个问题,是之前项目启动时用的临时appid,对照下小程序编辑器详情里的appid与公众平台里的appid是否一致

**Comment by bestyxie** [comment]
请检查一下配置是否正确。另外，微信接口的问题，偶尔也会出现的这样的现象。试试重启开发者工具。
