### ISSUE TITLE
如何调整HTML中的图片布局和文字排版？写css没有用。。。

### ISSUE THREAD

**Issue by cjy37** [ifanrx/wxParser-plugin#19]
如何调整HTML中的图片布局？我怎么写css都没有用

还有富文本中的排版，我改css也没有用的

**Comment by cjy37** [comment]
是我的错，style设置了scoped引起的

**Comment by fuguxu** [comment]
你是如何修改样式的 ，我用的taro.js 改了样式不生效呢
