### ISSUE TITLE
是否可以支持外部class

### ISSUE THREAD

**Issue by u9646** [ifanrx/wxParser-plugin#23]
您好，我在使用该插件的过程中，遇到这样一个问题：

比如有这样一段富文本，
```
<span style="font-size:16px"><strong>测试文本</strong></span>
```

我需要在外部对`span`, `strong`标签定义一些统一的样式，比如span { margin: 10px 0} ，这种。

请问这种可以实现吗，或者有其它的解决方案吗？

**Comment by bestyxie** [comment]
支持的，可以给标签定义 class ，在 wxss 里面写相关的样式

**Comment by bestyxie** [comment]
最新版本已经支持了
