### ISSUE TITLE
找不到插件：wepy-plugin-wxparserPlugin。

### ISSUE THREAD

**Issue by GavinDon** [ifanrx/wxParser-plugin#24]
使用wepy 框架引入的 npm run dev　之后 提示
[WARNING] 找不到插件：wepy-plugin-wxparserPlugin。
[16:13:51] [错误] 不存在插件：wepy-plugin-wxparserPlugin，请检测是否拼写错误。

**Comment by heshiyou** [comment]
wxParser 没有主动适配 wepy，建议去微信开发者社区查看 wepy 引入小程序插件的的支持。

**Comment by GavinDon** [comment]
> wxParser 没有主动适配 wepy，建议去微信开发者社区查看 wepy 引入小程序插件的的支持。
什么意思 ？是wepy 用不了wxparser-plugin?

**Comment by heshiyou** [comment]
wxparser-plugin 提供了对微信小程序的标准支持（小程序插件、js lib），但未测试 wepy 的工作情况。请自行测试 wepy 对使用标准的小程序插件的情况，如果 wepy 支持使用小程序插件，那应该可以使用 wxparser-plugin。
