### ISSUE TITLE
在request微信公众号的文章地址后显示script 的内容

### ISSUE THREAD

**Issue by vikingsailor** [ifanrx/wxParser-plugin#5]
在request微信公众号的文章地址后，用<wxparser rich-text="{{richText}}"></wxparser>显示

<script nonce="582805830" type="text/javascript">
--
  | window.logs = {
  | pagetime: {}
  | };
  | window.logs.pagetime['html_begin'] = (+new Date());
  | </script>
的内容，如何处理？

https://mp.weixin.qq.com/s?src=11&timestamp=1525576155&ver=859&signature=jahJW5itiG92La5arjkyrD4Su1GZ1s9*4VPpBJ0Oew4-i3yMJ6hBi9EAbusaHHNHKCNz-kPfltgg5BIOVQPZ9T9OK-LWKUYcy5GlpulgT4CCGFNYR56Bc4P0a94-0zNQ&new=1

**Comment by YaoKaiLun** [comment]
请具体描述下的问题
